### ISSUE TITLE
[bazel] Got "missing strict dependencies" when use protoc-gen-grpc-gateway as bazel-gazelle grpc compiler

### ISSUE THREAD

**Issue by asv** [grpc-ecosystem/grpc-gateway#1941]
## 🐛 Bug Report

I want to use protoc-gen-grpc-gateway as grpc_compiler to generate code in my bazel project.
For this Im specify protoc-gen-grpc-gateway as compiler for my grpc protos.

```
# gazelle:go_grpc_compilers @com_github_grpc_ecosystem_grpc_gateway_v2//protoc-gen-grpc-gateway:go_gen_grpc_gateway                                                                            
gazelle(                                                                                                                                                                                       
    name = "gazelle",                                                                                                                                                                          
)
```

 When I try to generate the code using `bazel build //proto/...`, I get the following error:

```
$ bazelisk build  //proto/...
INFO: Analyzed 3 targets (1 packages loaded, 3 targets configured).
INFO: Found 3 targets...
ERROR: /home/asmirnov/.cache/bazel/_bazel_asmirnov/e3c23bb5a397a370f5928992b61209fd/external/com_github_grpc_ecosystem_grpc_gateway_v2/protoc-gen-openapiv2/options/BUILD.bazel:15:11: GoCompilePkg external/com_github_grpc_ecosystem_grpc_gateway_v2/protoc-gen-openapiv2/options/go_default_library.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 47 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 47 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /home/asmirnov/.cache/bazel/_bazel_asmirnov/e3c23bb5a397a370f5928992b61209fd/sandbox/linux-sandbox/657/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_github_grpc_ecosystem_grpc_gateway_v2/protoc-gen-openapiv2/options/options_go_proto_/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options/annotations.pb.go: import of "google.golang.org/protobuf/types/descriptorpb"
        /home/asmirnov/.cache/bazel/_bazel_asmirnov/e3c23bb5a397a370f5928992b61209fd/sandbox/linux-sandbox/657/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_github_grpc_ecosystem_grpc_gateway_v2/protoc-gen-openapiv2/options/options_go_proto_/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options/openapiv2.pb.go: import of "google.golang.org/protobuf/types/known/structpb"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
INFO: Elapsed time: 7.732s, Critical Path: 2.91s
INFO: 22 processes: 6 internal, 16 linux-sandbox.
FAILED: Build did NOT complete successfully
```

reprorep: https://github.com/asv/grpc_gw_bazel_bug

## To Reproduce

1. git clone https://github.com/asv/grpc_gw_bazel_bug
2. cd grpc_gw_bazel_bug
3. bazel build //proto/...

## Expected behavior

`bazel build` completed successful.

## Actual Behavior

`bazel build` failed with error "missing strict dependencies".

## Your Environment

```
$ uname -ra
Linux asmirnov 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ bazelisk version
Bazelisk version: v1.4.0
Build label: 3.7.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:29:16 2020 (1603200556)
Build timestamp: 1603200556
Build timestamp as int: 160320055
```
protobuf 3.14
rules_go 0.25.1
bazel-gazelle 0.22.3

**Comment by johanbrandhorst** [comment]
Hi @asv, we provide out-of-the-box bazel rules for the grpc-gateway, see https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/BUILD.bazel#L24. I'm not sure exactly what's wrong with your setup, but you shouldn't have to go through all this effort. Could you try using our existing rule and see if that fixes your issue?

**Comment by asv** [comment]
@johanbrandhorst of course i'm using provided grpc-gateway bazel rules: https://github.com/asv/grpc_gw_bazel_bug/blob/main/proto/BUILD.bazel#L14

**Comment by johanbrandhorst** [comment]
Ah, sorry. The error implies some sort of mismatch between APIv2 imports (using google.golang.org) and the apiv1 imports using (github.com/golang.protobuf)? Can you try to reproduce the error using the same WORKSPACE versions we use in this repo and see if that fixes anything? https://github.com/grpc-ecosystem/grpc-gateway/blob/master/WORKSPACE. We may not be compatible with v0.25.1 of rules_go yet.

**Comment by asv** [comment]
With rules version from grpc-gateway WORKSPACE works, but had a downgrade protobuf_deps (your version from git, mine - current stable release 3.14) :(. Good news is that it didn't seem to break anything in my app.

What is the procedure for updating grpc-gateway dependencies? Is it enough to just update some dependencies and run the tests on the project?

**Comment by achew22** [comment]
Yep, that's all it should take

**Comment by asv** [comment]
Still breaks. Not at compilation, but at runtime:

```
panic: duplicate registration of "google/protobuf/field_mask.proto"

The generated definition for this file has moved:
        from: "google.golang.org/genproto/protobuf/field_mask"
        to:   "google.golang.org/protobuf/types/known/fieldmaskpb"
A dependency on the "google.golang.org/genproto" module must
be at version cb27e3aa (May 26th, 2020) or higher.

Upgrade the dependency by running:
        go get -u google.golang.org/genproto/protobuf/field_mask


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0000efee0, 0xe26b60, 0xc00026d500, 0x0, 0x0)
        external/org_golang_google_protobuf/reflect/protoregistry/registry.go:117 +0x1310
google.golang.org/protobuf/internal/filedesc.Builder.Build(0xbbc923, 0x32, 0x1255de0, 0xed, 0xed, 0x100000000, 0x0, 0xe108c0, 0xc00007f080, 0xe190e0, ...)
        external/org_golang_google_protobuf/internal/filedesc/build.go:110 +0x1aa
google.golang.org/protobuf/internal/filetype.Builder.Build(0xbbc923, 0x32, 0x1255de0, 0xed, 0xed, 0x100000000, 0x0, 0x0, 0x0, 0xe190e0, ...)
        external/org_golang_google_protobuf/internal/filetype/build.go:139 +0x178
google.golang.org/protobuf/types/known/fieldmaskpb.file_google_protobuf_field_mask_proto_init()
        external/org_golang_google_protobuf/types/known/fieldmaskpb/field_mask.pb.go:583 +0x1b8
google.golang.org/protobuf/types/known/fieldmaskpb.init.0()
        external/org_golang_google_protobuf/types/known/fieldmaskpb/field_mask.pb.go:551 +0x25
```

version genproto (at godeps.bzl) v0.0.0-20210204154452-deb828366460.

**Comment by johanbrandhorst** [comment]
We're still using some old path imports in our field mask logic, I believe it's actually blocked on either rules_go or google.golang.org/protobuf, but I can't remember. A test of this would be to try and replace all the uses of the old import paths in the `runtime` package and see if you can get bazel building. I might give it a go this weekend, but it wasn't possible when I was first working on this migration last year.
