### ISSUE TITLE
Crash when upgrading to Go 1.21

### ISSUE THREAD

**Issue by HirdrWit** [grpc-ecosystem/grpc-gateway#3658]
## 🐛 Bug Report

Experiencing the following crash when using --grpc-gateway-v2_out with Go 1.21. I am not able to reproduce when downgrading to Go 1.20.
`panic: invalid type: got *dynamicpb.Message, want *options.JSONSchema`

## To Reproduce

(Write your steps here:)

1. Upgrade your proto generation to use grpc-gateway-v2_out
1. Run the protoc generate cmd/script
1. See errors

## Expected behavior

Generate the code as normal. 

## Actual Behavior

`panic: invalid type: got *dynamicpb.Message, want *options.JSONSchema`
```
goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.(*messageConverter).GoValueOf(0x40003568e0, {{}, 0x459cc0?, 0x40000cc780?, 0x50b420?})
        /go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/impl/convert.go:457 +0x3a8
google.golang.org/protobuf/internal/impl.(*ExtensionInfo).InterfaceOf(0x400068c000?, {{}, 0x459cc0?, 0x40000cc780?, 0x50dd70?})
        /go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/impl/extension.go:102 +0x60
google.golang.org/protobuf/proto.GetExtension({0x505b88?, 0x400068c000?}, {0x50b420, 0x7dec40})
        /go/pkg/mod/google.golang.org/protobuf@v1.31.0/proto/extension.go:45 +0xb4
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.extractJSONSchemaFromFieldDescriptor(0x400068a000)
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/template.go:2588 +0x68
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.getFieldOpenAPIOption(0x4000138000, 0x4000713560)
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/template.go:2728 +0x2c
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.schemaOfField(_, _, _)
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/template.go:799 +0x704
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.renderServices({0x4000044310, 0x1, 0x0?}, 0x40007220f8, 0x4000138000, 0x0?, 0x0?, {0x4000717140, 0x5, 0x8})
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/template.go:1189 +0x2018
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.applyTemplate({0x40003c4900, 0x4000138000})
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/template.go:1745 +0x214
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi.(*generator).Generate(0x4000507d40, {0x4000044318?, 0xa?, 0x7e54e0?})
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/internal/genopenapi/generator.go:378 +0x17c
main.main()
        /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.17.0/protoc-gen-openapiv2/main.go:197 +0xed0
--openapiv2_out: protoc-gen-openapiv2: Plugin failed with status code 2.
generate.go:14: running "bash": exit status 1
```

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! This appears to have been introduced sometime between 2.17.0 and 2.15.0. Are you saying it doesn't reproduce on Go 1.20?

**Comment by HirdrWit** [comment]
Correct! However, it seems more likely that we have conflicting openapiv2 and openapiv1 references in our protos. We use a docker image to run go generate, I am not 100% sure why that change with updated dependencies in the docker image would cause one to panic and the other to compile, but a compile-time error is better than runtime. We are going to refrain from using openapiv2 until we move everything off of openapiv1.

**Comment by johanbrandhorst** [comment]
Could you provide a sample repo that reproduces this issue?

**Comment by Allan-Nava** [comment]
> Could you provide a sample repo that reproduces this issue?

I solved

**Comment by johanbrandhorst** [comment]
Thanks for getting back, maybe you could explain what you were doing wrong to help others?

**Comment by FotiadisM** [comment]
I am facing the same bug when annotating any Message, Field, or Method to add additional swagger information.

protoc-gen-go version `v1.36.5`
protoc-gen-openapiv2 version `v2.26.0`
